### ISSUE TITLE
Some badges are broken

### ISSUE THREAD

**Issue by gokaygurcan** [smtaydemir/rates#4]
Dumb badges didn't work right. 
I guess best course of action is pushing this update to _npm_ and adding LICENSE file to the repository. npm update would solve npm and devDepencencies badges, after adding the license file, license badge needs to be updated manually. 

Sorry for complications, it's hard to guess what will happen in someone else's repository when they merge your changes :smile: 

Cheers

**Comment by smtaydemir** [comment]
hahaha no problem, thanks :smile:
